package com.cyg.newbee_mall.pojo;

public class AdminUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_admin_user.admin_user_id
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Integer adminUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_admin_user.login_user_name
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String loginUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_admin_user.login_password
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_admin_user.nick_name
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_admin_user.locked
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Byte locked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_admin_user.admin_user_id
     *
     * @return the value of tb_newbee_mall_admin_user.admin_user_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Integer getAdminUserId() {
        return adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_admin_user.admin_user_id
     *
     * @param adminUserId the value for tb_newbee_mall_admin_user.admin_user_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setAdminUserId(Integer adminUserId) {
        this.adminUserId = adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_admin_user.login_user_name
     *
     * @return the value of tb_newbee_mall_admin_user.login_user_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getLoginUserName() {
        return loginUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_admin_user.login_user_name
     *
     * @param loginUserName the value for tb_newbee_mall_admin_user.login_user_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setLoginUserName(String loginUserName) {
        this.loginUserName = loginUserName == null ? null : loginUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_admin_user.login_password
     *
     * @return the value of tb_newbee_mall_admin_user.login_password
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_admin_user.login_password
     *
     * @param loginPassword the value for tb_newbee_mall_admin_user.login_password
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_admin_user.nick_name
     *
     * @return the value of tb_newbee_mall_admin_user.nick_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_admin_user.nick_name
     *
     * @param nickName the value for tb_newbee_mall_admin_user.nick_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_admin_user.locked
     *
     * @return the value of tb_newbee_mall_admin_user.locked
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Byte getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_admin_user.locked
     *
     * @param locked the value for tb_newbee_mall_admin_user.locked
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setLocked(Byte locked) {
        this.locked = locked;
    }
}