package com.cyg.newbee_mall.pojo;

import java.util.Date;

public class GoodsCatefory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.category_id
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.category_level
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Byte categoryLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.parent_id
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.category_name
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.category_rank
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Integer categoryRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.is_deleted
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.create_time
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.create_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.update_time
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_category.update_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Integer updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.category_id
     *
     * @return the value of tb_newbee_mall_goods_category.category_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.category_id
     *
     * @param categoryId the value for tb_newbee_mall_goods_category.category_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.category_level
     *
     * @return the value of tb_newbee_mall_goods_category.category_level
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Byte getCategoryLevel() {
        return categoryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.category_level
     *
     * @param categoryLevel the value for tb_newbee_mall_goods_category.category_level
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setCategoryLevel(Byte categoryLevel) {
        this.categoryLevel = categoryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.parent_id
     *
     * @return the value of tb_newbee_mall_goods_category.parent_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.parent_id
     *
     * @param parentId the value for tb_newbee_mall_goods_category.parent_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.category_name
     *
     * @return the value of tb_newbee_mall_goods_category.category_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.category_name
     *
     * @param categoryName the value for tb_newbee_mall_goods_category.category_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.category_rank
     *
     * @return the value of tb_newbee_mall_goods_category.category_rank
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Integer getCategoryRank() {
        return categoryRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.category_rank
     *
     * @param categoryRank the value for tb_newbee_mall_goods_category.category_rank
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setCategoryRank(Integer categoryRank) {
        this.categoryRank = categoryRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.is_deleted
     *
     * @return the value of tb_newbee_mall_goods_category.is_deleted
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.is_deleted
     *
     * @param isDeleted the value for tb_newbee_mall_goods_category.is_deleted
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.create_time
     *
     * @return the value of tb_newbee_mall_goods_category.create_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.create_time
     *
     * @param createTime the value for tb_newbee_mall_goods_category.create_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.create_user
     *
     * @return the value of tb_newbee_mall_goods_category.create_user
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.create_user
     *
     * @param createUser the value for tb_newbee_mall_goods_category.create_user
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.update_time
     *
     * @return the value of tb_newbee_mall_goods_category.update_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.update_time
     *
     * @param updateTime the value for tb_newbee_mall_goods_category.update_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_category.update_user
     *
     * @return the value of tb_newbee_mall_goods_category.update_user
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_category.update_user
     *
     * @param updateUser the value for tb_newbee_mall_goods_category.update_user
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }
}