package com.cyg.newbee_mall.pojo;

import java.util.Date;

public class IndexConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.config_id
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Long configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.config_name
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.config_type
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Byte configType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.goods_id
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.redirect_url
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String redirectUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.config_rank
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Integer configRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.is_deleted
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.create_time
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.create_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.update_time
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_index_config.update_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Integer updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.config_id
     *
     * @return the value of tb_newbee_mall_index_config.config_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Long getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.config_id
     *
     * @param configId the value for tb_newbee_mall_index_config.config_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.config_name
     *
     * @return the value of tb_newbee_mall_index_config.config_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.config_name
     *
     * @param configName the value for tb_newbee_mall_index_config.config_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.config_type
     *
     * @return the value of tb_newbee_mall_index_config.config_type
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Byte getConfigType() {
        return configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.config_type
     *
     * @param configType the value for tb_newbee_mall_index_config.config_type
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setConfigType(Byte configType) {
        this.configType = configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.goods_id
     *
     * @return the value of tb_newbee_mall_index_config.goods_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.goods_id
     *
     * @param goodsId the value for tb_newbee_mall_index_config.goods_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.redirect_url
     *
     * @return the value of tb_newbee_mall_index_config.redirect_url
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getRedirectUrl() {
        return redirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.redirect_url
     *
     * @param redirectUrl the value for tb_newbee_mall_index_config.redirect_url
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl == null ? null : redirectUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.config_rank
     *
     * @return the value of tb_newbee_mall_index_config.config_rank
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Integer getConfigRank() {
        return configRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.config_rank
     *
     * @param configRank the value for tb_newbee_mall_index_config.config_rank
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setConfigRank(Integer configRank) {
        this.configRank = configRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.is_deleted
     *
     * @return the value of tb_newbee_mall_index_config.is_deleted
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.is_deleted
     *
     * @param isDeleted the value for tb_newbee_mall_index_config.is_deleted
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.create_time
     *
     * @return the value of tb_newbee_mall_index_config.create_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.create_time
     *
     * @param createTime the value for tb_newbee_mall_index_config.create_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.create_user
     *
     * @return the value of tb_newbee_mall_index_config.create_user
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.create_user
     *
     * @param createUser the value for tb_newbee_mall_index_config.create_user
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.update_time
     *
     * @return the value of tb_newbee_mall_index_config.update_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.update_time
     *
     * @param updateTime the value for tb_newbee_mall_index_config.update_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_index_config.update_user
     *
     * @return the value of tb_newbee_mall_index_config.update_user
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_index_config.update_user
     *
     * @param updateUser the value for tb_newbee_mall_index_config.update_user
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }
}