package com.cyg.newbee_mall.pojo;

import java.util.Date;

public class MallUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user.user_id
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user.nick_name
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user.login_name
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user.password_md5
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String passwordMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user.introduce_sign
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String introduceSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user.address
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user.is_deleted
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user.locked_flag
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Byte lockedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_user.create_time
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user.user_id
     *
     * @return the value of tb_newbee_mall_user.user_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user.user_id
     *
     * @param userId the value for tb_newbee_mall_user.user_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user.nick_name
     *
     * @return the value of tb_newbee_mall_user.nick_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user.nick_name
     *
     * @param nickName the value for tb_newbee_mall_user.nick_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user.login_name
     *
     * @return the value of tb_newbee_mall_user.login_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user.login_name
     *
     * @param loginName the value for tb_newbee_mall_user.login_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user.password_md5
     *
     * @return the value of tb_newbee_mall_user.password_md5
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getPasswordMd5() {
        return passwordMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user.password_md5
     *
     * @param passwordMd5 the value for tb_newbee_mall_user.password_md5
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setPasswordMd5(String passwordMd5) {
        this.passwordMd5 = passwordMd5 == null ? null : passwordMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user.introduce_sign
     *
     * @return the value of tb_newbee_mall_user.introduce_sign
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getIntroduceSign() {
        return introduceSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user.introduce_sign
     *
     * @param introduceSign the value for tb_newbee_mall_user.introduce_sign
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setIntroduceSign(String introduceSign) {
        this.introduceSign = introduceSign == null ? null : introduceSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user.address
     *
     * @return the value of tb_newbee_mall_user.address
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user.address
     *
     * @param address the value for tb_newbee_mall_user.address
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user.is_deleted
     *
     * @return the value of tb_newbee_mall_user.is_deleted
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user.is_deleted
     *
     * @param isDeleted the value for tb_newbee_mall_user.is_deleted
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user.locked_flag
     *
     * @return the value of tb_newbee_mall_user.locked_flag
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Byte getLockedFlag() {
        return lockedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user.locked_flag
     *
     * @param lockedFlag the value for tb_newbee_mall_user.locked_flag
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setLockedFlag(Byte lockedFlag) {
        this.lockedFlag = lockedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_user.create_time
     *
     * @return the value of tb_newbee_mall_user.create_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_user.create_time
     *
     * @param createTime the value for tb_newbee_mall_user.create_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}