package com.cyg.newbee_mall.pojo;

import java.util.Date;

public class NewBeeMallGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.goods_id
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.goods_name
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.goods_intro
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String goodsIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.goods_category_id
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Long goodsCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.goods_cover_img
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String goodsCoverImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.goods_carousel
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String goodsCarousel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.original_price
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Integer originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.selling_price
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Integer sellingPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.stock_num
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Integer stockNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.tag
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.goods_sell_status
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Byte goodsSellStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.create_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.create_time
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.update_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.update_time
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_goods_info.goods_detail_content
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private String goodsDetailContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.goods_id
     *
     * @return the value of tb_newbee_mall_goods_info.goods_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.goods_id
     *
     * @param goodsId the value for tb_newbee_mall_goods_info.goods_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.goods_name
     *
     * @return the value of tb_newbee_mall_goods_info.goods_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.goods_name
     *
     * @param goodsName the value for tb_newbee_mall_goods_info.goods_name
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.goods_intro
     *
     * @return the value of tb_newbee_mall_goods_info.goods_intro
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getGoodsIntro() {
        return goodsIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.goods_intro
     *
     * @param goodsIntro the value for tb_newbee_mall_goods_info.goods_intro
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setGoodsIntro(String goodsIntro) {
        this.goodsIntro = goodsIntro == null ? null : goodsIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.goods_category_id
     *
     * @return the value of tb_newbee_mall_goods_info.goods_category_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Long getGoodsCategoryId() {
        return goodsCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.goods_category_id
     *
     * @param goodsCategoryId the value for tb_newbee_mall_goods_info.goods_category_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setGoodsCategoryId(Long goodsCategoryId) {
        this.goodsCategoryId = goodsCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.goods_cover_img
     *
     * @return the value of tb_newbee_mall_goods_info.goods_cover_img
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getGoodsCoverImg() {
        return goodsCoverImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.goods_cover_img
     *
     * @param goodsCoverImg the value for tb_newbee_mall_goods_info.goods_cover_img
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setGoodsCoverImg(String goodsCoverImg) {
        this.goodsCoverImg = goodsCoverImg == null ? null : goodsCoverImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.goods_carousel
     *
     * @return the value of tb_newbee_mall_goods_info.goods_carousel
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getGoodsCarousel() {
        return goodsCarousel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.goods_carousel
     *
     * @param goodsCarousel the value for tb_newbee_mall_goods_info.goods_carousel
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setGoodsCarousel(String goodsCarousel) {
        this.goodsCarousel = goodsCarousel == null ? null : goodsCarousel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.original_price
     *
     * @return the value of tb_newbee_mall_goods_info.original_price
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Integer getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.original_price
     *
     * @param originalPrice the value for tb_newbee_mall_goods_info.original_price
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setOriginalPrice(Integer originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.selling_price
     *
     * @return the value of tb_newbee_mall_goods_info.selling_price
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Integer getSellingPrice() {
        return sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.selling_price
     *
     * @param sellingPrice the value for tb_newbee_mall_goods_info.selling_price
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setSellingPrice(Integer sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.stock_num
     *
     * @return the value of tb_newbee_mall_goods_info.stock_num
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Integer getStockNum() {
        return stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.stock_num
     *
     * @param stockNum the value for tb_newbee_mall_goods_info.stock_num
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setStockNum(Integer stockNum) {
        this.stockNum = stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.tag
     *
     * @return the value of tb_newbee_mall_goods_info.tag
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.tag
     *
     * @param tag the value for tb_newbee_mall_goods_info.tag
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.goods_sell_status
     *
     * @return the value of tb_newbee_mall_goods_info.goods_sell_status
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Byte getGoodsSellStatus() {
        return goodsSellStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.goods_sell_status
     *
     * @param goodsSellStatus the value for tb_newbee_mall_goods_info.goods_sell_status
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setGoodsSellStatus(Byte goodsSellStatus) {
        this.goodsSellStatus = goodsSellStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.create_user
     *
     * @return the value of tb_newbee_mall_goods_info.create_user
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.create_user
     *
     * @param createUser the value for tb_newbee_mall_goods_info.create_user
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.create_time
     *
     * @return the value of tb_newbee_mall_goods_info.create_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.create_time
     *
     * @param createTime the value for tb_newbee_mall_goods_info.create_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.update_user
     *
     * @return the value of tb_newbee_mall_goods_info.update_user
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.update_user
     *
     * @param updateUser the value for tb_newbee_mall_goods_info.update_user
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.update_time
     *
     * @return the value of tb_newbee_mall_goods_info.update_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.update_time
     *
     * @param updateTime the value for tb_newbee_mall_goods_info.update_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_goods_info.goods_detail_content
     *
     * @return the value of tb_newbee_mall_goods_info.goods_detail_content
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public String getGoodsDetailContent() {
        return goodsDetailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_goods_info.goods_detail_content
     *
     * @param goodsDetailContent the value for tb_newbee_mall_goods_info.goods_detail_content
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setGoodsDetailContent(String goodsDetailContent) {
        this.goodsDetailContent = goodsDetailContent == null ? null : goodsDetailContent.trim();
    }
}