package com.cyg.newbee_mall.pojo;

import java.util.Date;

public class NewBeeMallShoppingCartItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_shopping_cart_item.cart_item_id
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Long cartItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_shopping_cart_item.user_id
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_shopping_cart_item.goods_id
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_shopping_cart_item.goods_count
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Integer goodsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_shopping_cart_item.is_deleted
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_shopping_cart_item.create_time
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_newbee_mall_shopping_cart_item.update_time
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_shopping_cart_item.cart_item_id
     *
     * @return the value of tb_newbee_mall_shopping_cart_item.cart_item_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Long getCartItemId() {
        return cartItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_shopping_cart_item.cart_item_id
     *
     * @param cartItemId the value for tb_newbee_mall_shopping_cart_item.cart_item_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setCartItemId(Long cartItemId) {
        this.cartItemId = cartItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_shopping_cart_item.user_id
     *
     * @return the value of tb_newbee_mall_shopping_cart_item.user_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_shopping_cart_item.user_id
     *
     * @param userId the value for tb_newbee_mall_shopping_cart_item.user_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_shopping_cart_item.goods_id
     *
     * @return the value of tb_newbee_mall_shopping_cart_item.goods_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_shopping_cart_item.goods_id
     *
     * @param goodsId the value for tb_newbee_mall_shopping_cart_item.goods_id
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_shopping_cart_item.goods_count
     *
     * @return the value of tb_newbee_mall_shopping_cart_item.goods_count
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_shopping_cart_item.goods_count
     *
     * @param goodsCount the value for tb_newbee_mall_shopping_cart_item.goods_count
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_shopping_cart_item.is_deleted
     *
     * @return the value of tb_newbee_mall_shopping_cart_item.is_deleted
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_shopping_cart_item.is_deleted
     *
     * @param isDeleted the value for tb_newbee_mall_shopping_cart_item.is_deleted
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_shopping_cart_item.create_time
     *
     * @return the value of tb_newbee_mall_shopping_cart_item.create_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_shopping_cart_item.create_time
     *
     * @param createTime the value for tb_newbee_mall_shopping_cart_item.create_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_newbee_mall_shopping_cart_item.update_time
     *
     * @return the value of tb_newbee_mall_shopping_cart_item.update_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_newbee_mall_shopping_cart_item.update_time
     *
     * @param updateTime the value for tb_newbee_mall_shopping_cart_item.update_time
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}