package com.cyg.newbee_mall.mapper;

import com.cyg.newbee_mall.pojo.AdminUser;
import com.cyg.newbee_mall.pojo.AdminUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int countByExample(AdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int deleteByExample(AdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int deleteByPrimaryKey(Integer adminUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int insert(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int insertSelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    List<AdminUser> selectByExample(AdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    AdminUser selectByPrimaryKey(Integer adminUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByExampleSelective(@Param("record") AdminUser record, @Param("example") AdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByExample(@Param("record") AdminUser record, @Param("example") AdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByPrimaryKeySelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_admin_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByPrimaryKey(AdminUser record);
}