package com.cyg.newbee_mall.mapper;

import com.cyg.newbee_mall.pojo.GoodsCatefory;
import com.cyg.newbee_mall.pojo.GoodsCateforyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GoodsCateforyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_goods_category
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int countByExample(GoodsCateforyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_goods_category
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int deleteByExample(GoodsCateforyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_goods_category
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int deleteByPrimaryKey(Long categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_goods_category
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int insert(GoodsCatefory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_goods_category
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int insertSelective(GoodsCatefory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_goods_category
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    List<GoodsCatefory> selectByExample(GoodsCateforyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_goods_category
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    GoodsCatefory selectByPrimaryKey(Long categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_goods_category
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByExampleSelective(@Param("record") GoodsCatefory record, @Param("example") GoodsCateforyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_goods_category
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByExample(@Param("record") GoodsCatefory record, @Param("example") GoodsCateforyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_goods_category
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByPrimaryKeySelective(GoodsCatefory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_goods_category
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByPrimaryKey(GoodsCatefory record);
}