package com.cyg.newbee_mall.mapper;

import com.cyg.newbee_mall.pojo.IndexConfig;
import com.cyg.newbee_mall.pojo.IndexConfigExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IndexConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int countByExample(IndexConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int deleteByExample(IndexConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int deleteByPrimaryKey(Long configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int insert(IndexConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int insertSelective(IndexConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    List<IndexConfig> selectByExample(IndexConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    IndexConfig selectByPrimaryKey(Long configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByExampleSelective(@Param("record") IndexConfig record, @Param("example") IndexConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByExample(@Param("record") IndexConfig record, @Param("example") IndexConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByPrimaryKeySelective(IndexConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_index_config
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByPrimaryKey(IndexConfig record);
}