package com.cyg.newbee_mall.mapper;

import com.cyg.newbee_mall.pojo.MallUser;
import com.cyg.newbee_mall.pojo.MallUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MallUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int countByExample(MallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int deleteByExample(MallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int insert(MallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int insertSelective(MallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    List<MallUser> selectByExample(MallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    MallUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByExampleSelective(@Param("record") MallUser record, @Param("example") MallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByExample(@Param("record") MallUser record, @Param("example") MallUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByPrimaryKeySelective(MallUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_user
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByPrimaryKey(MallUser record);
}