package com.cyg.newbee_mall.mapper;

import com.cyg.newbee_mall.pojo.NewBeeMallOrder;
import com.cyg.newbee_mall.pojo.NewBeeMallOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface NewBeeMallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_order
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int countByExample(NewBeeMallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_order
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int deleteByExample(NewBeeMallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_order
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_order
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int insert(NewBeeMallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_order
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int insertSelective(NewBeeMallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_order
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    List<NewBeeMallOrder> selectByExample(NewBeeMallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_order
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    NewBeeMallOrder selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_order
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByExampleSelective(@Param("record") NewBeeMallOrder record, @Param("example") NewBeeMallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_order
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByExample(@Param("record") NewBeeMallOrder record, @Param("example") NewBeeMallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_order
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByPrimaryKeySelective(NewBeeMallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_order
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByPrimaryKey(NewBeeMallOrder record);
}