package com.cyg.newbee_mall.mapper;

import com.cyg.newbee_mall.pojo.NewBeeMallShoppingCartItem;
import com.cyg.newbee_mall.pojo.NewBeeMallShoppingCartItemExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface NewBeeMallShoppingCartItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_shopping_cart_item
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int countByExample(NewBeeMallShoppingCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_shopping_cart_item
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int deleteByExample(NewBeeMallShoppingCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_shopping_cart_item
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int deleteByPrimaryKey(Long cartItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_shopping_cart_item
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int insert(NewBeeMallShoppingCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_shopping_cart_item
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int insertSelective(NewBeeMallShoppingCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_shopping_cart_item
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    List<NewBeeMallShoppingCartItem> selectByExample(NewBeeMallShoppingCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_shopping_cart_item
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    NewBeeMallShoppingCartItem selectByPrimaryKey(Long cartItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_shopping_cart_item
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByExampleSelective(@Param("record") NewBeeMallShoppingCartItem record, @Param("example") NewBeeMallShoppingCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_shopping_cart_item
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByExample(@Param("record") NewBeeMallShoppingCartItem record, @Param("example") NewBeeMallShoppingCartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_shopping_cart_item
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByPrimaryKeySelective(NewBeeMallShoppingCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_newbee_mall_shopping_cart_item
     *
     * @mbggenerated Thu Dec 09 19:17:31 CST 2021
     */
    int updateByPrimaryKey(NewBeeMallShoppingCartItem record);
}